import mongoose from "mongoose";

const IfYouLikedSchema = new mongoose.Schema({
    slug: {
        type: String,
        required: true,
        unique: true,
        index: true, // Optimizes lookups by slug
    },
    mediaType: {
        type: String,
        required: true,
        enum: ["movie", "tv"],
    },
    mediaId: {
        type: Number,
        required: true,
    },
    title: {
        type: String,
        required: true,
    },
    // The catchy headline generated by LLM (e.g. "If you loved the mass action...")
    headline: {
        type: String,
        required: false, // Optional for backward compatibility, but generally populated
    },
    // The Markdown content generated by the LLM
    content: {
        type: String,
        required: true,
    },
    bannerUrl: {
        type: String,
        required: false
    },
    // Persist the recommendations used/shown in the article to avoid fetching again
    recommendations: [
        {
            id: Number,
            title: String,
            name: String, // for TV
            poster_path: String,
            backdrop_path: String,
            release_date: String,
            first_air_date: String,
            media_type: String,
            vote_average: Number,
            overview: String,
        }
    ],
    createdAt: {
        type: Date,
        default: Date.now,
    },
});

// Helper to prevent overwriting model during hot-reloads in dev
export default mongoose.models.IfYouLiked || mongoose.model("IfYouLiked", IfYouLikedSchema);
